2025-05-04 03:06:19,838 - pacman-server - INFO - PacmanServicer initialized on port 50052 with data directory ./data/raft_50052
2025-05-04 03:06:19,838 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/raft_50051
2025-05-04 03:06:19,838 - pacman-server - INFO - Started game tick loop (this node is the leader)
2025-05-04 03:06:19,840 - pacman-server - INFO - Server started on port 50051
2025-05-04 03:06:19,840 - pacman-server - INFO - Server started on port 50052
2025-05-04 03:06:20,322 - pacman-server - INFO - PacmanServicer initialized on port 50053 with data directory ./data/raft_50053
2025-05-04 03:06:20,324 - pacman-server - INFO - Server started on port 50053
2025-05-04 03:06:20,854 - pacman-server - INFO - PacmanServicer initialized on port 50054 with data directory ./data/raft_50054
2025-05-04 03:06:20,855 - pacman-server - INFO - Server started on port 50054
2025-05-04 03:06:21,382 - pacman-server - INFO - PacmanServicer initialized on port 50055 with data directory ./data/raft_50055
2025-05-04 03:06:21,383 - pacman-server - INFO - Server started on port 50055
2025-05-04 03:07:46,954 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 03:07:46,954 - pacman-server - INFO - Started game tick loop
2025-05-04 03:07:46,955 - pacman-server - INFO - Server started on port 50051
2025-05-04 03:08:01,846 - pacman-server - INFO - Server stopping...
2025-05-04 03:08:24,907 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 03:08:24,907 - pacman-server - INFO - Started game tick loop
2025-05-04 03:08:24,908 - pacman-server - INFO - Server started on port 50051
2025-05-04 03:09:43,183 - pacman-server - INFO - Server stopping...
2025-05-04 03:09:54,283 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 03:09:54,283 - pacman-server - INFO - Started game tick loop
2025-05-04 03:09:54,285 - pacman-server - INFO - Server started on port 50051
2025-05-04 03:10:30,779 - pacman-server - INFO - Created new game: c8467caf-bbff-4c68-82bd-68eff7a8ce7f, layout: default, max players: 2
2025-05-04 03:12:50,066 - pacman-server - INFO - Player d5e95d43 joined game c8467caf-bbff-4c68-82bd-68eff7a8ce7f
2025-05-04 03:22:21,838 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 03:22:21,839 - pacman-server - INFO - Started game tick loop
2025-05-04 03:22:21,841 - pacman-server - INFO - Server started on port 50051
2025-05-04 03:22:52,784 - pacman-server - INFO - Created new game: 525c856d-e9d4-42a3-a92b-e0c95f7449e0, layout: mediumClassic, max players: 2
2025-05-04 03:23:11,660 - pacman-server - INFO - Player d190601a joined game 525c856d-e9d4-42a3-a92b-e0c95f7449e0
2025-05-04 03:23:11,784 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
    for action in request_iterator:
  File "/Users/pedrogarcia/.pyenv/versions/3.9.18/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/Users/pedrogarcia/.pyenv/versions/3.9.18/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/Users/pedrogarcia/.pyenv/versions/3.9.18/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/pedrogarcia/.pyenv/versions/3.9.18/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 03:23:12,663 - pacman-server - INFO - PlayGame stream ended for player d190601a in game 525c856d-e9d4-42a3-a92b-e0c95f7449e0
2025-05-04 03:26:03,788 - pacman-server - INFO - Created new game: 3224d69c-02d5-4287-a014-8d61b766c88f, layout: mediumClassic, max players: 2
2025-05-04 03:26:15,632 - pacman-server - INFO - Player a37b681a joined game 3224d69c-02d5-4287-a014-8d61b766c88f
2025-05-04 03:26:41,213 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
    for action in request_iterator:
  File "/Users/pedrogarcia/.pyenv/versions/3.9.18/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/Users/pedrogarcia/.pyenv/versions/3.9.18/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/Users/pedrogarcia/.pyenv/versions/3.9.18/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/Users/pedrogarcia/.pyenv/versions/3.9.18/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 03:26:41,739 - pacman-server - INFO - PlayGame stream ended for player a37b681a in game 3224d69c-02d5-4287-a014-8d61b766c88f
2025-05-04 09:07:01,572 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 09:07:01,573 - pacman-server - INFO - Started game tick loop
2025-05-04 09:07:01,576 - pacman-server - INFO - Server started on port 50051
2025-05-04 09:10:04,194 - pacman-server - INFO - Created new game: 21a37f69-1edf-4767-b4b3-e504746af5df, layout: mediumClassic, max players: 2
2025-05-04 09:10:18,248 - pacman-server - INFO - Player 904d8ac3 joined game 21a37f69-1edf-4767-b4b3-e504746af5df
2025-05-04 09:10:30,102 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 09:10:30,269 - pacman-server - INFO - PlayGame stream ended for player 904d8ac3 in game 21a37f69-1edf-4767-b4b3-e504746af5df
2025-05-04 09:12:28,394 - pacman-server - INFO - Created new game: 6968b693-ea64-4aae-9143-24b1da1eb577, layout: mediumClassic, max players: 2
2025-05-04 09:12:39,878 - pacman-server - INFO - Player 72f2eecf joined game 6968b693-ea64-4aae-9143-24b1da1eb577
2025-05-04 09:14:50,722 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 09:14:51,342 - pacman-server - INFO - PlayGame stream ended for player 72f2eecf in game 6968b693-ea64-4aae-9143-24b1da1eb577
2025-05-04 09:15:00,685 - pacman-server - INFO - Created new game: d2c6878d-05ad-4528-8318-67e43b5f38e8, layout: mediumClassic, max players: 1
2025-05-04 09:15:08,491 - pacman-server - INFO - Player d6ffcfb3 joined game d2c6878d-05ad-4528-8318-67e43b5f38e8
2025-05-04 09:15:56,395 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 09:15:57,388 - pacman-server - INFO - PlayGame stream ended for player d6ffcfb3 in game d2c6878d-05ad-4528-8318-67e43b5f38e8
2025-05-04 09:16:06,708 - pacman-server - INFO - Created new game: 851cd92c-3a60-4781-9f5e-6726aa465e05, layout: mediumClassic, max players: 1
2025-05-04 09:16:13,544 - pacman-server - INFO - Player b8486d18 joined game 851cd92c-3a60-4781-9f5e-6726aa465e05
2025-05-04 09:18:14,513 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 09:18:15,507 - pacman-server - INFO - PlayGame stream ended for player b8486d18 in game 851cd92c-3a60-4781-9f5e-6726aa465e05
2025-05-04 09:18:21,748 - pacman-server - INFO - Created new game: 1db5da60-5d09-4c2a-98fc-dd9b2fc7a3b2, layout: mediumClassic, max players: 1
2025-05-04 09:18:30,538 - pacman-server - INFO - Player d7865f42 joined game 1db5da60-5d09-4c2a-98fc-dd9b2fc7a3b2
2025-05-04 09:20:16,215 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 09:20:17,203 - pacman-server - INFO - PlayGame stream ended for player d7865f42 in game 1db5da60-5d09-4c2a-98fc-dd9b2fc7a3b2
2025-05-04 09:20:23,212 - pacman-server - INFO - Created new game: 7a80b5d7-ebf2-4801-80fc-5a4aefbb336c, layout: mediumClassic, max players: 1
2025-05-04 09:20:34,062 - pacman-server - INFO - Player 8e6cb9e7 joined game 7a80b5d7-ebf2-4801-80fc-5a4aefbb336c
2025-05-04 09:28:48,001 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
    """RPC method to create a new game"""
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 09:28:48,641 - pacman-server - INFO - Server stopping...
2025-05-04 09:28:48,996 - pacman-server - INFO - PlayGame stream ended for player 8e6cb9e7 in game 7a80b5d7-ebf2-4801-80fc-5a4aefbb336c
2025-05-04 09:28:50,817 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 09:28:50,817 - pacman-server - INFO - Started game tick loop
2025-05-04 09:28:50,819 - pacman-server - INFO - Server started on port 50051
2025-05-04 09:29:06,347 - pacman-server - INFO - Server stopping...
2025-05-04 09:29:08,358 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 09:29:08,358 - pacman-server - INFO - Started game tick loop
2025-05-04 09:29:08,360 - pacman-server - INFO - Server started on port 50051
2025-05-04 09:29:20,022 - pacman-server - ERROR - Error creating game: 'GameSession' object has no attribute 'update_loop'
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 261, in CreateGame
    new_game = GameSession(game_id, layout_name, max_players)
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 45, in __init__
    self.update_thread = threading.Thread(target=self.update_loop)
AttributeError: 'GameSession' object has no attribute 'update_loop'
2025-05-04 09:29:51,940 - pacman-server - INFO - Server stopping...
2025-05-04 09:29:54,135 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 09:29:54,135 - pacman-server - INFO - Started game tick loop
2025-05-04 09:29:54,137 - pacman-server - INFO - Server started on port 50051
2025-05-04 09:30:00,989 - pacman-server - ERROR - Error creating game: 'GameSession' object has no attribute 'update_loop'
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 261, in CreateGame
    new_game = GameSession(game_id, layout_name, max_players)
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 45, in __init__
    self.update_thread = threading.Thread(target=self.update_loop)
AttributeError: 'GameSession' object has no attribute 'update_loop'
2025-05-04 09:44:05,482 - pacman-server - INFO - Server stopping...
2025-05-04 09:44:29,243 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 09:44:29,243 - pacman-server - INFO - Started game tick loop
2025-05-04 09:44:29,246 - pacman-server - INFO - Server started on port 50051
2025-05-04 09:44:37,143 - pacman-server - INFO - Created new game session c8c1b3c5-7257-48b0-a52f-7dd6c582c7b7
2025-05-04 09:44:37,144 - pacman-server - INFO - Created new game: c8c1b3c5-7257-48b0-a52f-7dd6c582c7b7, layout: mediumClassic, max players: 1
2025-05-04 09:44:45,410 - pacman-server - INFO - Player 704cc925 joined as PACMAN
2025-05-04 09:44:45,410 - pacman-server - INFO - Player 704cc925 joined game c8c1b3c5-7257-48b0-a52f-7dd6c582c7b7
2025-05-04 09:55:45,727 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 09:55:45,810 - pacman-server - INFO - PlayGame stream ended for player 704cc925 in game c8c1b3c5-7257-48b0-a52f-7dd6c582c7b7
2025-05-04 09:55:46,829 - pacman-server - INFO - Server stopping...
2025-05-04 09:55:47,945 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 09:55:47,945 - pacman-server - INFO - Started game tick loop
2025-05-04 09:55:47,947 - pacman-server - INFO - Server started on port 50051
2025-05-04 09:56:03,492 - pacman-server - INFO - Server stopping...
2025-05-04 09:59:21,628 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/raft_50051
2025-05-04 09:59:21,629 - pacman-server - INFO - Started game tick loop
2025-05-04 09:59:21,631 - pacman-server - INFO - Server started on port 50051
2025-05-04 09:59:22,169 - pacman-server - INFO - PacmanServicer initialized on port 50052 with data directory ./data/raft_50052
2025-05-04 09:59:22,169 - pacman-server - INFO - Started game tick loop
2025-05-04 09:59:22,171 - pacman-server - INFO - Server started on port 50052
2025-05-04 09:59:22,700 - pacman-server - INFO - PacmanServicer initialized on port 50053 with data directory ./data/raft_50053
2025-05-04 09:59:22,700 - pacman-server - INFO - Started game tick loop
2025-05-04 09:59:22,702 - pacman-server - INFO - Server started on port 50053
2025-05-04 09:59:23,233 - pacman-server - INFO - PacmanServicer initialized on port 50054 with data directory ./data/raft_50054
2025-05-04 09:59:23,233 - pacman-server - INFO - Started game tick loop
2025-05-04 09:59:23,235 - pacman-server - INFO - Server started on port 50054
2025-05-04 09:59:23,759 - pacman-server - INFO - PacmanServicer initialized on port 50055 with data directory ./data/raft_50055
2025-05-04 09:59:23,759 - pacman-server - INFO - Started game tick loop
2025-05-04 09:59:23,761 - pacman-server - INFO - Server started on port 50055
2025-05-04 09:59:28,491 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/raft_50051
2025-05-04 09:59:28,491 - pacman-server - INFO - Started game tick loop
2025-05-04 09:59:28,493 - pacman-server - INFO - Server started on port 50051
2025-05-04 09:59:29,037 - pacman-server - INFO - PacmanServicer initialized on port 50052 with data directory ./data/raft_50052
2025-05-04 09:59:29,037 - pacman-server - INFO - Started game tick loop
2025-05-04 09:59:29,039 - pacman-server - INFO - Server started on port 50052
2025-05-04 09:59:29,537 - pacman-server - INFO - PacmanServicer initialized on port 50053 with data directory ./data/raft_50053
2025-05-04 09:59:29,537 - pacman-server - INFO - Started game tick loop
2025-05-04 09:59:29,539 - pacman-server - INFO - Server started on port 50053
2025-05-04 09:59:30,079 - pacman-server - INFO - PacmanServicer initialized on port 50054 with data directory ./data/raft_50054
2025-05-04 09:59:30,079 - pacman-server - INFO - Started game tick loop
2025-05-04 09:59:30,081 - pacman-server - INFO - Server started on port 50054
2025-05-04 09:59:30,607 - pacman-server - INFO - PacmanServicer initialized on port 50055 with data directory ./data/raft_50055
2025-05-04 09:59:30,608 - pacman-server - INFO - Started game tick loop
2025-05-04 09:59:30,610 - pacman-server - INFO - Server started on port 50055
2025-05-04 10:01:50,244 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/raft_50051
2025-05-04 10:01:50,244 - pacman-server - INFO - Started game tick loop
2025-05-04 10:01:50,246 - pacman-server - INFO - Server started on port 50051
2025-05-04 10:01:50,726 - pacman-server - INFO - PacmanServicer initialized on port 50052 with data directory ./data/raft_50052
2025-05-04 10:01:50,726 - pacman-server - INFO - Started game tick loop
2025-05-04 10:01:50,728 - pacman-server - INFO - Server started on port 50052
2025-05-04 10:01:51,225 - pacman-server - INFO - PacmanServicer initialized on port 50053 with data directory ./data/raft_50053
2025-05-04 10:01:51,226 - pacman-server - INFO - Started game tick loop
2025-05-04 10:01:51,228 - pacman-server - INFO - Server started on port 50053
2025-05-04 10:01:51,744 - pacman-server - INFO - PacmanServicer initialized on port 50054 with data directory ./data/raft_50054
2025-05-04 10:01:51,744 - pacman-server - INFO - Started game tick loop
2025-05-04 10:01:51,746 - pacman-server - INFO - Server started on port 50054
2025-05-04 10:01:57,771 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 10:01:57,771 - pacman-server - INFO - Started game tick loop
2025-05-04 10:01:57,773 - pacman-server - INFO - Server started on port 50051
2025-05-04 10:02:03,278 - pacman-server - INFO - Created new game session 723ba509-c2b3-45c2-84c3-c6e9de099a33
2025-05-04 10:02:03,278 - pacman-server - INFO - Created new game: 723ba509-c2b3-45c2-84c3-c6e9de099a33, layout: mediumClassic, max players: 1
2025-05-04 10:02:12,140 - pacman-server - INFO - Player 5b13af26 joined as PACMAN
2025-05-04 10:02:12,140 - pacman-server - INFO - Player 5b13af26 joined game 723ba509-c2b3-45c2-84c3-c6e9de099a33
2025-05-04 10:03:02,169 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:03:02,303 - pacman-server - INFO - PlayGame stream ended for player 5b13af26 in game 723ba509-c2b3-45c2-84c3-c6e9de099a33
2025-05-04 10:03:03,202 - pacman-server - INFO - Player 5b13af26 joined as PACMAN
2025-05-04 10:03:03,203 - pacman-server - INFO - Player 5b13af26 joined game 723ba509-c2b3-45c2-84c3-c6e9de099a33
2025-05-04 10:03:43,321 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:03:43,351 - pacman-server - INFO - PlayGame stream ended for player 5b13af26 in game 723ba509-c2b3-45c2-84c3-c6e9de099a33
2025-05-04 10:03:44,338 - pacman-server - INFO - Player 5b13af26 joined as PACMAN
2025-05-04 10:03:44,338 - pacman-server - INFO - Player 5b13af26 joined game 723ba509-c2b3-45c2-84c3-c6e9de099a33
2025-05-04 10:04:24,454 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:04:24,491 - pacman-server - INFO - PlayGame stream ended for player 5b13af26 in game 723ba509-c2b3-45c2-84c3-c6e9de099a33
2025-05-04 10:04:25,469 - pacman-server - INFO - Player 5b13af26 joined as PACMAN
2025-05-04 10:04:25,470 - pacman-server - INFO - Player 5b13af26 joined game 723ba509-c2b3-45c2-84c3-c6e9de099a33
2025-05-04 10:04:53,956 - pacman-server - INFO - Server stopping...
2025-05-04 10:04:53,959 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:04:54,581 - pacman-server - INFO - PlayGame stream ended for player 5b13af26 in game 723ba509-c2b3-45c2-84c3-c6e9de099a33
2025-05-04 10:11:30,329 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 10:11:30,329 - pacman-server - INFO - Started game tick loop
2025-05-04 10:11:30,332 - pacman-server - INFO - Server started on port 50051
2025-05-04 10:11:34,599 - pacman-server - INFO - Created new game session c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:11:34,600 - pacman-server - INFO - Created new game: c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28, layout: mediumClassic, max players: 1
2025-05-04 10:11:46,896 - pacman-server - INFO - Player f02a848d joined as PACMAN
2025-05-04 10:11:46,896 - pacman-server - INFO - Player f02a848d joined game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:12:36,919 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:12:37,091 - pacman-server - INFO - PlayGame stream ended for player f02a848d in game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:12:37,946 - pacman-server - INFO - Player f02a848d joined as PACMAN
2025-05-04 10:12:37,946 - pacman-server - INFO - Player f02a848d joined game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:13:18,072 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:13:18,099 - pacman-server - INFO - PlayGame stream ended for player f02a848d in game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:13:19,096 - pacman-server - INFO - Player f02a848d joined as PACMAN
2025-05-04 10:13:19,096 - pacman-server - INFO - Player f02a848d joined game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:13:59,208 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:13:59,251 - pacman-server - INFO - PlayGame stream ended for player f02a848d in game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:14:00,224 - pacman-server - INFO - Player f02a848d joined as PACMAN
2025-05-04 10:14:00,225 - pacman-server - INFO - Player f02a848d joined game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:14:40,348 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:14:40,348 - pacman-server - INFO - PlayGame stream ended for player f02a848d in game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:14:41,374 - pacman-server - INFO - Player f02a848d joined as PACMAN
2025-05-04 10:14:41,374 - pacman-server - INFO - Player f02a848d joined game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:15:21,484 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:15:21,502 - pacman-server - INFO - PlayGame stream ended for player f02a848d in game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:15:22,498 - pacman-server - INFO - Player f02a848d joined as PACMAN
2025-05-04 10:15:22,498 - pacman-server - INFO - Player f02a848d joined game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:16:02,616 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:16:02,641 - pacman-server - INFO - PlayGame stream ended for player f02a848d in game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:16:03,634 - pacman-server - INFO - Player f02a848d joined as PACMAN
2025-05-04 10:16:03,634 - pacman-server - INFO - Player f02a848d joined game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:16:43,760 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:16:43,764 - pacman-server - INFO - PlayGame stream ended for player f02a848d in game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:17:34,815 - pacman-server - ERROR - Error in PlayGame stream: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 588, in PlayGame
    logger.info(f"Created new game: {game_id}, layout: {layout_name}, max players: {max_players}")
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:17:34,819 - pacman-server - INFO - PlayGame stream ended for player None in game None
2025-05-04 10:17:35,833 - pacman-server - INFO - Player f02a848d joined as PACMAN
2025-05-04 10:17:35,833 - pacman-server - INFO - Player f02a848d joined game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:18:15,948 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:18:15,999 - pacman-server - INFO - PlayGame stream ended for player f02a848d in game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:18:16,960 - pacman-server - INFO - Player f02a848d joined as PACMAN
2025-05-04 10:18:16,960 - pacman-server - INFO - Player f02a848d joined game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:18:57,077 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:18:57,125 - pacman-server - INFO - PlayGame stream ended for player f02a848d in game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:18:58,093 - pacman-server - INFO - Player f02a848d joined as PACMAN
2025-05-04 10:18:58,093 - pacman-server - INFO - Player f02a848d joined game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:19:38,215 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:19:38,222 - pacman-server - INFO - PlayGame stream ended for player f02a848d in game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:19:39,229 - pacman-server - INFO - Player f02a848d joined as PACMAN
2025-05-04 10:19:39,229 - pacman-server - INFO - Player f02a848d joined game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:20:19,355 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:20:19,356 - pacman-server - INFO - PlayGame stream ended for player f02a848d in game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:21:10,401 - pacman-server - ERROR - Error in PlayGame stream: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 588, in PlayGame
    first_action = next(request_iterator)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:21:10,404 - pacman-server - INFO - PlayGame stream ended for player None in game None
2025-05-04 10:21:11,415 - pacman-server - INFO - Player f02a848d joined as PACMAN
2025-05-04 10:21:11,420 - pacman-server - INFO - Player f02a848d joined game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:21:51,531 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:21:51,565 - pacman-server - INFO - PlayGame stream ended for player f02a848d in game c9cadf52-b062-4cdb-8fa2-30ca3dbd6b28
2025-05-04 10:22:02,557 - pacman-server - INFO - Server stopping...
2025-05-04 10:22:02,562 - pacman-server - ERROR - Error in PlayGame stream: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 588, in PlayGame
    first_action = next(request_iterator)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:22:02,563 - pacman-server - INFO - PlayGame stream ended for player None in game None
2025-05-04 10:26:33,626 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 10:26:33,626 - pacman-server - INFO - Started game tick loop
2025-05-04 10:26:33,628 - pacman-server - INFO - Server started on port 50051
2025-05-04 10:26:41,421 - pacman-server - INFO - Created new game session 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:26:41,421 - pacman-server - INFO - Created new game: 076d0e54-a236-4c98-b9a4-9a0fbd6351c4, layout: mediumClassic, max players: 1
2025-05-04 10:26:47,134 - pacman-server - INFO - Player 27ae7b6f joined as PACMAN
2025-05-04 10:26:47,135 - pacman-server - INFO - Player 27ae7b6f joined game 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:27:37,157 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:27:37,322 - pacman-server - INFO - PlayGame stream ended for player 27ae7b6f in game 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:27:38,183 - pacman-server - INFO - Player 27ae7b6f joined as PACMAN
2025-05-04 10:27:38,183 - pacman-server - INFO - Player 27ae7b6f joined game 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:28:18,302 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:28:18,335 - pacman-server - INFO - PlayGame stream ended for player 27ae7b6f in game 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:28:19,318 - pacman-server - INFO - Player 27ae7b6f joined as PACMAN
2025-05-04 10:28:19,318 - pacman-server - INFO - Player 27ae7b6f joined game 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:28:59,442 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:29:00,438 - pacman-server - INFO - PlayGame stream ended for player 27ae7b6f in game 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:29:50,482 - pacman-server - ERROR - Error in PlayGame stream: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 588, in PlayGame
    first_action = next(request_iterator)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:29:50,484 - pacman-server - INFO - PlayGame stream ended for player None in game None
2025-05-04 10:29:51,499 - pacman-server - INFO - Player 27ae7b6f joined as PACMAN
2025-05-04 10:29:51,500 - pacman-server - INFO - Player 27ae7b6f joined game 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:30:31,618 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:30:31,636 - pacman-server - INFO - PlayGame stream ended for player 27ae7b6f in game 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:30:32,636 - pacman-server - INFO - Player 27ae7b6f joined as PACMAN
2025-05-04 10:30:32,638 - pacman-server - INFO - Player 27ae7b6f joined game 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:31:12,756 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:31:12,773 - pacman-server - INFO - PlayGame stream ended for player 27ae7b6f in game 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:32:03,806 - pacman-server - ERROR - Error in PlayGame stream: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 588, in PlayGame
    first_action = next(request_iterator)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:32:03,809 - pacman-server - INFO - PlayGame stream ended for player None in game None
2025-05-04 10:32:04,827 - pacman-server - INFO - Player 27ae7b6f joined as PACMAN
2025-05-04 10:32:04,827 - pacman-server - INFO - Player 27ae7b6f joined game 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:32:23,809 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:32:23,898 - pacman-server - INFO - PlayGame stream ended for player 27ae7b6f in game 076d0e54-a236-4c98-b9a4-9a0fbd6351c4
2025-05-04 10:32:46,451 - pacman-server - WARNING - Could not find layout 1, using mediumClassic as fallback
2025-05-04 10:32:46,452 - pacman-server - INFO - Created new game session d6bf3121-9c25-4d2b-a789-c802209af62b
2025-05-04 10:32:46,453 - pacman-server - INFO - Created new game: d6bf3121-9c25-4d2b-a789-c802209af62b, layout: 1, max players: 4
2025-05-04 10:32:50,022 - pacman-server - INFO - Player e18572cb joined as PACMAN
2025-05-04 10:32:50,023 - pacman-server - INFO - Player e18572cb joined game d6bf3121-9c25-4d2b-a789-c802209af62b
2025-05-04 10:36:13,423 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 627, in process_actions
    )
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:36:13,741 - pacman-server - INFO - PlayGame stream ended for player e18572cb in game d6bf3121-9c25-4d2b-a789-c802209af62b
2025-05-04 10:36:27,112 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data/server
2025-05-04 10:36:27,112 - pacman-server - INFO - Started game tick loop
2025-05-04 10:36:27,115 - pacman-server - INFO - Server started on port 50051
2025-05-04 10:37:31,892 - pacman-server - WARNING - Could not find layout default, using mediumClassic as fallback
2025-05-04 10:37:31,893 - pacman-server - INFO - Created new game session 99c486d8-a3e4-4bfa-9975-9f05599493ab
2025-05-04 10:37:31,894 - pacman-server - INFO - Created new game: 99c486d8-a3e4-4bfa-9975-9f05599493ab, layout: default, max players: 1
2025-05-04 10:37:34,054 - pacman-server - INFO - Player fda7c335 joined as PACMAN
2025-05-04 10:37:34,055 - pacman-server - INFO - Player fda7c335 joined game 99c486d8-a3e4-4bfa-9975-9f05599493ab
2025-05-04 10:38:00,536 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 635, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 488, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 480, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 462, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 162, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 10:38:01,163 - pacman-server - INFO - PlayGame stream ended for player fda7c335 in game 99c486d8-a3e4-4bfa-9975-9f05599493ab
2025-05-04 10:48:23,709 - pacman-server - INFO - Server stopping...
2025-05-04 10:48:59,960 - pacman-server - INFO - PacmanServicer initialized on port 50051
2025-05-04 10:48:59,962 - pacman-server - INFO - Server started on port 50051
2025-05-04 10:49:37,366 - pacman-server - WARNING - Could not find layout default, using mediumClassic as fallback
2025-05-04 10:49:37,369 - pacman-server - INFO - Created new game session 7439467b
2025-05-04 10:49:37,369 - pacman-server - INFO - Created new game 7439467b with layout default, max players 1
2025-05-04 10:49:39,493 - pacman-server - INFO - Player 7f15ab9a joined as PACMAN
2025-05-04 10:49:39,493 - pacman-server - INFO - Player 7f15ab9a joined game 7439467b
2025-05-04 10:49:39,494 - pacman-server - INFO - Player 7f15ab9a joined game 7439467b
2025-05-04 12:17:19,275 - pacman-server - INFO - Server stopping...
2025-05-04 12:17:19,287 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 573, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 488, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 480, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 462, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 162, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 12:17:19,292 - pacman-server - INFO - Player 7f15ab9a left game 7439467b. 0 players remain.
2025-05-04 12:17:19,292 - pacman-server - INFO - Game 7439467b ended - no players left
2025-05-04 12:17:20,018 - pacman-server - INFO - PlayGame stream ended for player 7f15ab9a in game 7439467b
2025-05-04 12:17:54,913 - pacman-server - INFO - PacmanServicer initialized on port 50051
2025-05-04 12:17:54,915 - pacman-server - INFO - Server started on port 50051
2025-05-04 12:21:14,925 - pacman-server - INFO - PacmanServicer initialized on port 50051
2025-05-04 12:21:14,927 - pacman-server - INFO - Server started on port 50051
2025-05-04 12:21:54,198 - pacman-server - WARNING - Could not find layout default, using mediumClassic as fallback
2025-05-04 12:21:54,199 - pacman-server - INFO - Created new game session b72f79cf
2025-05-04 12:21:54,199 - pacman-server - INFO - Created new game b72f79cf with layout default, max players 1
2025-05-04 12:21:55,746 - pacman-server - INFO - Player bcee4969 joined as PACMAN
2025-05-04 12:21:55,746 - pacman-server - INFO - Player bcee4969 joined game b72f79cf
2025-05-04 12:21:55,746 - pacman-server - INFO - Player bcee4969 joined game b72f79cf
2025-05-04 12:39:02,231 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 573, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 488, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 480, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 462, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 162, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 12:39:02,237 - pacman-server - INFO - Player bcee4969 left game b72f79cf. 0 players remain.
2025-05-04 12:39:02,237 - pacman-server - INFO - Game b72f79cf ended - no players left
2025-05-04 12:39:02,299 - pacman-server - INFO - Removing finished game b72f79cf
2025-05-04 12:39:02,726 - pacman-server - INFO - PlayGame stream ended for player bcee4969 in game b72f79cf
2025-05-04 12:39:06,871 - pacman-server - INFO - Server stopping...
2025-05-04 12:39:15,217 - pacman-server - INFO - PacmanServicer initialized on port 50051
2025-05-04 12:39:15,219 - pacman-server - INFO - Server started on port 50051
2025-05-04 12:46:37,290 - pacman-server - INFO - Server stopping...
2025-05-04 12:47:30,247 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 12:47:30,248 - pacman-server - INFO - Started game tick loop
2025-05-04 12:47:30,250 - pacman-server - INFO - Server started on port 50051
2025-05-04 12:47:37,914 - pacman-server - INFO - Created new game: 109b0979-3b28-4bc7-bfc5-78f426200786, layout: default, max players: 1
2025-05-04 12:47:43,951 - pacman-server - INFO - Player 769bd695 joined game 109b0979-3b28-4bc7-bfc5-78f426200786
2025-05-04 13:19:10,925 - pacman-server - INFO - Server stopping...
2025-05-04 13:19:10,933 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 488, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 480, in _next
    request = self._look_for_request()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 462, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/grpc/_server.py", line 162, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 13:19:11,911 - pacman-server - INFO - PlayGame stream ended for player 769bd695 in game 109b0979-3b28-4bc7-bfc5-78f426200786
2025-05-04 13:32:27,952 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 13:32:27,953 - pacman-server - INFO - Started game tick loop
2025-05-04 13:32:27,955 - pacman-server - INFO - Server started on port 50051
2025-05-04 13:32:39,498 - pacman-server - INFO - Created new game: 8adf1e2c-3ee1-4136-89c5-0a3504cb46ed, layout: default, max players: 3
2025-05-04 13:32:48,431 - pacman-server - INFO - Player 25f4ce91 joined game 8adf1e2c-3ee1-4136-89c5-0a3504cb46ed
2025-05-04 13:33:22,910 - pacman-server - INFO - Server stopping...
2025-05-04 13:33:22,915 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 13:33:25,268 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 13:33:25,268 - pacman-server - INFO - Started game tick loop
2025-05-04 13:33:25,270 - pacman-server - INFO - Server started on port 50051
2025-05-04 13:33:34,384 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 13:33:34,384 - pacman-server - INFO - Started game tick loop
2025-05-04 13:33:34,388 - pacman-server - INFO - Server started on port 50051
2025-05-04 13:33:35,088 - pacman-server - INFO - Server stopping...
2025-05-04 13:33:45,513 - pacman-server - INFO - Created new game: 7706c863-02e7-4973-a4a8-f0785e42022f, layout: default, max players: 2
2025-05-04 13:33:52,617 - pacman-server - INFO - Player fc03c60f joined game 7706c863-02e7-4973-a4a8-f0785e42022f
2025-05-04 13:33:54,278 - pacman-server - INFO - Player 03d04095 joined game 7706c863-02e7-4973-a4a8-f0785e42022f
2025-05-04 13:45:51,455 - pacman-server - INFO - Server stopping...
2025-05-04 13:45:51,458 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 13:45:51,458 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 13:48:18,055 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 13:48:18,055 - pacman-server - INFO - Started game tick loop
2025-05-04 13:48:18,058 - pacman-server - INFO - Server started on port 50051
2025-05-04 13:55:48,919 - pacman-server - INFO - Server stopping...
2025-05-04 13:55:54,335 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 13:55:54,336 - pacman-server - INFO - Started game tick loop
2025-05-04 13:55:54,338 - pacman-server - INFO - Server started on port 50051
2025-05-04 13:56:01,826 - pacman-server - INFO - Created new game: 35ee993a-0df0-4d24-8edc-6c0e0c226621, layout: mediumClassic, max players: 4
2025-05-04 13:56:04,850 - pacman-server - INFO - Player 2b12e587 joined game 35ee993a-0df0-4d24-8edc-6c0e0c226621
2025-05-04 13:56:04,959 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 13:56:05,855 - pacman-server - INFO - PlayGame stream ended for player 2b12e587 in game 35ee993a-0df0-4d24-8edc-6c0e0c226621
2025-05-04 13:58:32,776 - pacman-server - INFO - Server stopping...
2025-05-04 14:00:28,427 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 14:00:28,427 - pacman-server - INFO - Started game tick loop
2025-05-04 14:00:28,430 - pacman-server - INFO - Server started on port 50051
2025-05-04 14:00:35,278 - pacman-server - INFO - Created new game: 5929637b-a09e-43e7-86a8-968f5a0cc7ea, layout: mediumClassic, max players: 4
2025-05-04 14:00:36,897 - pacman-server - INFO - Player 0c52536d joined game 5929637b-a09e-43e7-86a8-968f5a0cc7ea
2025-05-04 14:05:44,677 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 246, in process_actions
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 14:05:44,930 - pacman-server - INFO - PlayGame stream ended for player 0c52536d in game 5929637b-a09e-43e7-86a8-968f5a0cc7ea
2025-05-04 14:05:45,511 - pacman-server - INFO - Server stopping...
2025-05-04 14:05:48,878 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 14:05:48,880 - pacman-server - INFO - Server started on port 50051
2025-05-04 14:05:52,199 - pacman-server - INFO - Created new game session bdd7c0f3-2bde-4dd0-98c2-74302a4f9918
2025-05-04 14:05:52,200 - pacman-server - INFO - Created new game: bdd7c0f3-2bde-4dd0-98c2-74302a4f9918, layout: mediumClassic, max players: 4
2025-05-04 14:05:53,739 - pacman-server - INFO - Player f06b51ef joined as PACMAN
2025-05-04 14:05:53,739 - pacman-server - INFO - Player f06b51ef joined game bdd7c0f3-2bde-4dd0-98c2-74302a4f9918
2025-05-04 14:07:34,886 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 549, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 14:07:35,086 - pacman-server - INFO - PlayGame stream ended for player f06b51ef in game bdd7c0f3-2bde-4dd0-98c2-74302a4f9918
2025-05-04 14:07:36,807 - pacman-server - INFO - Server stopping...
2025-05-04 14:07:48,685 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 14:07:48,687 - pacman-server - INFO - Server started on port 50051
2025-05-04 14:07:56,994 - pacman-server - INFO - Created new game session 414f2975-e461-4c93-a6f1-7f0ca650e61a
2025-05-04 14:07:56,994 - pacman-server - INFO - Created new game: 414f2975-e461-4c93-a6f1-7f0ca650e61a, layout: mediumClassic, max players: 4
2025-05-04 14:08:00,739 - pacman-server - INFO - Player 59e59e6e joined as PACMAN
2025-05-04 14:08:00,739 - pacman-server - INFO - Player 59e59e6e joined game 414f2975-e461-4c93-a6f1-7f0ca650e61a
2025-05-04 14:08:04,818 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 549, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 14:08:05,764 - pacman-server - INFO - PlayGame stream ended for player 59e59e6e in game 414f2975-e461-4c93-a6f1-7f0ca650e61a
2025-05-04 14:08:12,996 - pacman-server - INFO - Created new game session dd4982b8-d915-417b-b9bb-069d5727daab
2025-05-04 14:08:12,997 - pacman-server - INFO - Created new game: dd4982b8-d915-417b-b9bb-069d5727daab, layout: mediumClassic, max players: 4
2025-05-04 14:08:38,603 - pacman-server - INFO - Player 25dc0d9c joined as PACMAN
2025-05-04 14:08:38,603 - pacman-server - INFO - Player 25dc0d9c joined game dd4982b8-d915-417b-b9bb-069d5727daab
2025-05-04 14:08:49,047 - pacman-server - INFO - Player ddf6e191 joined as GHOST
2025-05-04 14:08:49,048 - pacman-server - INFO - Player ddf6e191 joined game dd4982b8-d915-417b-b9bb-069d5727daab
2025-05-04 14:08:49,073 - pacman-server - ERROR - Error in game update loop: module 'pacman_pb2' has no attribute 'Agent'
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 222, in update_loop
    self.broadcast_game_state()
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 347, in broadcast_game_state
    game_state = self._create_game_state()
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 403, in _create_game_state
    agent = pacman_pb2.Agent(
AttributeError: module 'pacman_pb2' has no attribute 'Agent'
2025-05-04 14:09:22,510 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 549, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 14:09:22,511 - pacman-server - INFO - Player ddf6e191 is now PACMAN
2025-05-04 14:09:22,768 - pacman-server - INFO - PlayGame stream ended for player 25dc0d9c in game dd4982b8-d915-417b-b9bb-069d5727daab
2025-05-04 14:09:44,598 - pacman-server - INFO - Player 8e794730 joined as GHOST
2025-05-04 14:09:44,599 - pacman-server - INFO - Player 8e794730 joined game dd4982b8-d915-417b-b9bb-069d5727daab
2025-05-04 14:14:16,111 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 549, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 14:14:16,112 - pacman-server - INFO - Player 8e794730 is now PACMAN
2025-05-04 14:14:16,190 - pacman-server - INFO - PlayGame stream ended for player ddf6e191 in game dd4982b8-d915-417b-b9bb-069d5727daab
2025-05-04 14:14:16,886 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 549, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 14:14:17,568 - pacman-server - INFO - PlayGame stream ended for player 8e794730 in game dd4982b8-d915-417b-b9bb-069d5727daab
2025-05-04 14:21:26,406 - pacman-server - INFO - Server stopping...
2025-05-04 14:21:28,255 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 14:21:28,257 - pacman-server - INFO - Server started on port 50051
2025-05-04 14:21:36,407 - pacman-server - INFO - Created new game session 34f11317-de92-4d31-8c96-7130d7b4724d
2025-05-04 14:21:36,408 - pacman-server - INFO - Created new game: 34f11317-de92-4d31-8c96-7130d7b4724d, layout: mediumClassic, max players: 4
2025-05-04 14:21:38,185 - pacman-server - INFO - Player 874fb746 joined as PACMAN
2025-05-04 14:21:38,185 - pacman-server - INFO - Player 874fb746 joined game 34f11317-de92-4d31-8c96-7130d7b4724d
2025-05-04 14:21:38,185 - pacman-server - ERROR - Error in PlayGame stream: module 'pacman_pb2' has no attribute 'Agent'
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 546, in PlayGame
    initial_state = game._create_game_state()
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 403, in _create_game_state
    agent = pacman_pb2.Agent(
AttributeError: module 'pacman_pb2' has no attribute 'Agent'
2025-05-04 14:21:38,185 - pacman-server - INFO - PlayGame stream ended for player 874fb746 in game 34f11317-de92-4d31-8c96-7130d7b4724d
2025-05-04 14:24:18,324 - pacman-server - INFO - Server stopping...
2025-05-04 14:24:21,997 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 14:24:21,999 - pacman-server - INFO - Server started on port 50051
2025-05-04 14:24:28,405 - pacman-server - INFO - Created new game session ebd88eb9-d3c5-43cc-9214-81026cd08175
2025-05-04 14:24:28,406 - pacman-server - INFO - Created new game: ebd88eb9-d3c5-43cc-9214-81026cd08175, layout: mediumClassic, max players: 4
2025-05-04 14:24:30,620 - pacman-server - INFO - Player fe825930 joined as PACMAN
2025-05-04 14:24:30,620 - pacman-server - INFO - Player fe825930 joined game ebd88eb9-d3c5-43cc-9214-81026cd08175
2025-05-04 14:29:04,790 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 551, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 14:29:05,323 - pacman-server - INFO - Server stopping...
2025-05-04 14:29:05,435 - pacman-server - INFO - PlayGame stream ended for player fe825930 in game ebd88eb9-d3c5-43cc-9214-81026cd08175
2025-05-04 14:29:10,691 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 14:29:10,694 - pacman-server - INFO - Server started on port 50051
2025-05-04 14:29:13,329 - pacman-server - INFO - Created new game session a1688fdf-43bf-4126-b089-41ee90507bf8
2025-05-04 14:29:13,329 - pacman-server - INFO - Created new game: a1688fdf-43bf-4126-b089-41ee90507bf8, layout: mediumClassic, max players: 4
2025-05-04 14:29:26,658 - pacman-server - INFO - Player 57cd1f84 joined as PACMAN
2025-05-04 14:29:26,658 - pacman-server - INFO - Player 57cd1f84 joined game a1688fdf-43bf-4126-b089-41ee90507bf8
2025-05-04 14:46:34,946 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 551, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 14:46:35,288 - pacman-server - INFO - PlayGame stream ended for player 57cd1f84 in game a1688fdf-43bf-4126-b089-41ee90507bf8
2025-05-04 14:50:58,814 - pacman-server - INFO - Server stopping...
2025-05-04 14:51:04,955 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 14:51:04,957 - pacman-server - INFO - Server started on port 50051
2025-05-04 14:51:16,245 - pacman-server - INFO - Created new game session 54485418-41a2-45eb-9795-ca4bc0c9496c
2025-05-04 14:51:16,245 - pacman-server - INFO - Created new game: 54485418-41a2-45eb-9795-ca4bc0c9496c, layout: mediumClassic, max players: 4
2025-05-04 14:51:17,664 - pacman-server - INFO - Player f4824d6c joined as PACMAN
2025-05-04 14:51:17,665 - pacman-server - INFO - Player f4824d6c joined game 54485418-41a2-45eb-9795-ca4bc0c9496c
2025-05-04 14:54:37,775 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 551, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 14:54:38,398 - pacman-server - INFO - PlayGame stream ended for player f4824d6c in game 54485418-41a2-45eb-9795-ca4bc0c9496c
2025-05-04 14:58:47,922 - pacman-server - INFO - Server stopping...
2025-05-04 15:04:41,682 - pacman-server - INFO - PacmanServicer initialized on port 50051 with data directory ./data
2025-05-04 15:04:41,685 - pacman-server - INFO - Server started on port 50051
2025-05-04 15:04:51,433 - pacman-server - INFO - Created new game session bdf71990-90d2-4a2e-96a6-6312509f8952
2025-05-04 15:04:51,434 - pacman-server - INFO - Created new game: bdf71990-90d2-4a2e-96a6-6312509f8952, layout: mediumClassic, max players: 4
2025-05-04 15:04:53,509 - pacman-server - INFO - Player 3e552ca1 joined as PACMAN
2025-05-04 15:04:53,509 - pacman-server - INFO - Player 3e552ca1 joined game bdf71990-90d2-4a2e-96a6-6312509f8952
2025-05-04 15:04:56,422 - pacman-server - ERROR - Error processing player actions: 
Traceback (most recent call last):
  File "/Users/pedrogarcia/pAIc-man/pacman_server.py", line 551, in process_actions
    for action in request_iterator:
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 543, in __next__
    return self._next()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 535, in _next
    request = self._look_for_request()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 517, in _look_for_request
    _raise_rpc_error(self._state)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/paic-man/lib/python3.9/site-packages/grpc/_server.py", line 217, in _raise_rpc_error
    raise rpc_error
grpc.RpcError
2025-05-04 15:04:56,515 - pacman-server - INFO - PlayGame stream ended for player 3e552ca1 in game bdf71990-90d2-4a2e-96a6-6312509f8952
2025-05-04 15:04:57,797 - pacman-server - INFO - Server stopping...
